### ISSUE TITLE
経路一覧を表示しているのに、各経路の数字ボタンもアクティブ（青色）になっている

### ISSUE THREAD

**Issue by marochin** [EkispertWebService/GUI#18]
# サンプルコードへのご意見・ご要望

## サンプルコード名
探索結果ツール（expGuiCourse）

## 概要
「結果一覧」ボタンと、経路番号のボタンが同時にアクティブ（青色）な状態になっている

## 再現手順
・探索をすると、まず経路一覧が表示されるが、その時点で「結果一覧」と「1」のボタンが両方とも青色になっている（「1」はまだクリックしてないのに青色になっているのが違和感を感じました）

・その後、「2」をクリックして2番目の経路を表示し、そして「結果一覧」ボタンをクリック
→この時も「2」のボタンが青色のままなのが違和感を感じました

## 修正案
「結果一覧」が表示されている時は、「結果一覧」ボタンのみアクティブな色にする

**Comment by hmaruyama** [comment]
「結果一覧」を押した後、もう一度「結果一覧」を押すと探索結果に戻る仕様です。

※オン・オフが可能なボタンです。
そのため、未選択状態だと2回目の「結果一覧」を押した際に表示する経路が特定できなくなりますので、もう一度「結果一覧」を押したときに表示する経路のタブがアクティブになっています。

**Comment by marochin** [comment]
@hmaruyama なるほど、作りとしてそういうふうにしてるんですね。
ご説明いただき、ありがとうございます。
